### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Akitsu-G** [Akitsu-G/furima-29634#10]
よろしくお願いします。

項目 | 内容
-- | --
URL | https://furima-29634.herokuapp.com/
BASIC_AUTH_USER | Akitsu
BASIC_AUTH_PASSWORD | Decaf
出品者(Seller)mail, pass | seller@mail.jp, seller123
購入者(Buyer)mail, pass | buyer@mail.jp, buyer123
カード番号・cvc・有効期限 | 4242424242424242, 123, 3月33年

**Comment by TECHCAMP555** [comment]
Akitsu-G さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・クレジットカード決済ができる
→いただいている情報を入力してもエラーになり購入ができません。
<img width="488" alt="スクリーンショット 2021-01-22 17 55 45" src="https://user-images.githubusercontent.com/69237012/105469242-46c76d00-5cdb-11eb-8912-6083bb14ee85.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TECHCAMP555** [comment]
Akitsu-G さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
